### ISSUE TITLE
unpin napari?

### ISSUE THREAD

**Issue by tlambert03** [alisterburt/napari-tomoslice#7]
Howdie!

I'm obsessively trying to make `npe2 fetch` (https://github.com/napari/npe2/pull/185) work for as many plugins as I can.  This one and napari-subboxer are both failing because they pin napari to 0.4.12 ... which unfortunately doesn't work with `npe2`, since it imports some private stuff that got removed.  is it conceivable to unpin here and at subboxer?  or did we break too much for you?

**Comment by alisterburt** [comment]
Hey there! Does removing this one from the hub work for you? It was a playground for the plane controls before they were well integrated in napari and is now deprecated

Subboxer I need to update and haven't got around to it but I'm happy to remove that from the hub too if it helps you out - I don't think installing it from pip would work now anyway because of vispy changes 

Thanks!

**Comment by tlambert03** [comment]
> Does removing this one from the hub work for you?

sure, but it's also definitely not a big deal if you still want it up there for any reason... we don't _really_ need to hit them all :)

**Comment by alisterburt** [comment]
small update here - have emailed the hub team and both plugins should be removed from the hub shortly :) closing here, feel free to reopen if this hasn't happened soon and I'll follow up
